### ISSUE TITLE
Question || Feature Request: Setting Custom DataTable Options via Django View?

### ISSUE THREAD

**Issue by mdstaff** [pivotal-energy-solutions/django-datatable-view#105]
I couldn't find an easy way to turn off searching and pagination dynamically so I modified the datatableview.js file as follows:

```
...
$(function () {
    if (datatableview.auto_initialize) {
        var opts = {
            "searching": false,
            "paging": false
        };
        datatableview.initialize($('.datatable'), opts);
    }
}
```

Is it possible to expose the datatableview.initialize() opts parameter?  If not I think it would be really useful if the existing DatatableView.datatable_options dictionary could add data properties to the html table which the datatableview.js file could detect for simple boolean flags like searching and paging.

Thanks again,
Matt

**Comment by tiliv** [comment]
There is a janky global function you can define to intercept the final options object before it is sent to the ``dataTable()`` constructor, but it's getting dropped in the upcoming release in favor of avoiding automatic initialization.

Conceivably you could modify the ``datatableview.defaults`` object to accomplish this same thing across all tables, if you need to have control over it per initialization, sending it explicitly will be the official way to go.

To make it clearer where one might change this if they look at the code, I'm adding a global default for sorting.  Searching is different because dataTables.js has you specify it per column; you could set a different ``sDom`` value to get rid of the search field entirely.  All of the settings available to you in dataTables.js are allowed in the the ``datatableview.defaults`` or during manual initialization, since they're just being forwarded to the library.  If you have questions about any of those settings, I'd recommend their documentation.
