### ISSUE TITLE
Default processors for django model field types

### ISSUE THREAD

**Issue by doganmeh** [pivotal-energy-solutions/django-datatable-view#158]
This follows from pr #157.

I plan on using this helper along with the `make_boolean_checkmark` helper a lot. Basically show all boolean fields as checkmarks and all (ForeignKey'ed) related models as links. So every datatable created will most probably have several of these combined. 

Therefore, it would be very convenient, if I could assign default processors for these field types (i.e., BooleanField, and ForeignKey). Such as:

```
default_processors = [ 
    boolean = ..
    foreign_key = ..
```

This would save some typing, as it will not be necessary to type processors for each and every such column. 

Then specific processors defined as usual (for other types, or to override the defaults if need be):

```
processors = [ ...
```

Default processors would probably be put in a parent class,  thus making configuration much easier. I used these two types, but there could be others as well.

**Comment by tiliv** [comment]
Sorry for such a long silence.  I think you can do this by defining your own custom column:

Something like...

```python
from datatableview import columns, helpers

class BooleanCheckmarkColumn(columns.BooleanColumn):
    def __init__(self, *args, **kwargs):
        kwargs['processor'] = helpers.make_boolean_checkmark
        super(BooleanCheckmarkColumn, self).__init__(*args, **kwargs)
```

Custom columns always register themselves as the newest top priority for the types they handle.  You don't have to worry about specifying those types because you're just subclassing an existing one.

**Comment by doganmeh** [comment]
Can I override the Datatable or DatatableView class so the Boolean model
fields get the BooleanCheckmarkColumn by default? As you might see, I am
after uniform behavior accross my app.

**Comment by tiliv** [comment]
Ah, sorry, I left out that part of the explanation.  Subclassing a built-in column like this will make it the new top priority column class for the modelfields it handles.  That means that (unless you declare a table with columns using an explicit reference to ``columns.BooleanColumn``, all boolean fields will end up using ``BooleanCheckmarkColumn`` by default.

**Comment by tiliv** [comment]
I should note that this is probably an area of the code I intend to improve upon in a future update, because I'm not thrilled that simply defining a subclass make it the global default.  I think I'll have to add an explicit utility function in order to let you register it as the new default on purpose rather than by accident.

**Comment by doganmeh** [comment]
Either way sounds great for me..

**Comment by doganmeh** [comment]
How would the datatableview know I have overriden a column class (somewhere
in my codebase) though, when I have not defined my columns expilicitly?

> Custom columns always register themselves as the newest top priority for
the types they handle.

This probably refers to it, but it is not clear to me how it happens.


On Tue, Feb 28, 2017 at 7:10 AM Mehmet Dogan <mehmetdogantx@gmail.com>
wrote:

Either way sounds great for me..
On Tue, Feb 28, 2017 at 12:29 AM Tim Valenta <notifications@github.com>
wrote:

I should note that this is probably an area of the code I intend to improve
upon in a future update, because I'm not thrilled that simply defining a
subclass make it the global default. I think I'll have to add an explicit
utility function in order to let you register it as the new default on
purpose rather than by accident.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pivotal-energy-solutions/django-datatable-view/issues/158#issuecomment-282954500>,
or mute the thread

**Comment by tiliv** [comment]
The built-in Column classes add themselves to a private list, and each Column has an attribute called ``handles_field_classes`` that is a list of the modelfields it can query for searches.  (BooleanColumn lists ``models.BooleanField`` and ``models.NullBooleanField`` for example, because you query those the same way in the database.)

Using the following example:

```python
class MyDatatable(Datatable):
    class Meta:
        model = BlogEntry
        columns = ['id', 'name', 'is_published']
```

At this stage, the column system doesn't know anything about ``is_published``, so it looks up the field on the model.  It discovers that it's a Django ``BooleanField``, but it still needs to look up a Column class to handle BooleanFields.  It iterates over the private column registry until it finds a Column class with a ``handles_field_classes`` list that contains the model field BooleanField.

Normally, it iterates the registry until it finds the built-in BooleanColumn, but if you declare a new column class, it goes into the top of the registry with top priority, and will be found first.

As a counter-example, this Datatable would respect your choice for BooleanColumn because you've provided it explicitly:

```python
class MyDatatable(Datatable):
    is_published = columns.BooleanColumn("Published")

    class Meta:
        model = BlogEntry
        columns = ['id', 'name', 'is_published']
```

Hopefully that clarifies it!

**Comment by doganmeh** [comment]
Kind of.. When does the custom Column adds itself to the list, when I
import it into the same namespace as the DatatableView class? Because
custom Column lives in an arbitrary place in my codebase and there is no
way the Datatable or the DatatableView classes knowing about it.

**Comment by tiliv** [comment]
As of right now, the Column base class uses a metaclass to do the registration at the time of declaration.  In effect that means all you have to do is import the column somewhere, and it gets registered automatically.

There are drawbacks to this, so when I add an explicit registration function and take away this automatic one, the metaclass will be removed.  I might do this sooner than later...

**Comment by doganmeh** [comment]
Now crystal clear. I can help with documentation if you want. There are a
lot of things written, but I think they could be better organized. And,
there might be things here and there not documented. Also, going forward,
we need to focus efforts on "one" syntax, I believe.

**Comment by tiliv** [comment]
I believe just about everything is documented at the readthedocs site, at least at the conceptual level, including this behavior: http://django-datatable-view.readthedocs.io/en/latest/topics/custom-columns.html

The question of how the registration works in all of its details isn't necessarily something I think belongs in that document.  I think the biggest weakness is probably knowing where in the docs to look to answer a given question.  For example, you started off wanting global processors on BooleanField, and it wasn't obvious that custom columns were the answer.  Not sure I can answer every question like that in the docs, but maybe an FAQ will help.

We lack concrete examples on the readthedocs site, but that's hopefully what the example project does for us (which I don't have running on AWS yet, but I intend to get that running soon).

**Comment by doganmeh** [comment]
Indeed it is there! Has probably escaped my attention because it is under
"third party model fields".
