### ISSUE TITLE
plain_value or default_value

### ISSUE THREAD

**Issue by doganmeh** [pivotal-energy-solutions/django-datatable-view#176]
Seems what is being referred to as 'default_value' in Datatable class and the helpers are being referred to as 'plain_value' in the Column class. If that is not on purpose, we can make them consistent by making them all 'default_value'. 

https://github.com/pivotal-energy-solutions/django-datatable-view/blob/master/datatableview/columns.py#L151

Also, docstring there explains the difference between plain/default values and the rich value, which I could not find in the docs. 

https://github.com/pivotal-energy-solutions/django-datatable-view/blob/master/datatableview/columns.py#L164

**Comment by tiliv** [comment]
You may be correct about a rename, but I'll say that the reason for the difference is that the Datatable class only knows about raw database values.  It's the Column's job to tidy up the value, optionally creating "pretty" versions.  Your suggestion about making them all ``default_value`` might be fine because it doesn't hurt this distinction.  Also, I think you're right about the documentation lacking an entry on the behavior.  It looks like I never got the relevant methods and attributes for Column listed in the docs.

On a side note (although I'd have to check to be sure) I think the processor functions get all of the mentioned values in ``kwargs``.  In a processor, it just so happens that ``default_value`` is usually the most practical raw value to work with.

**Comment by doganmeh** [comment]
processors do get both.

**Comment by doganmeh** [comment]
I created a commit for the rename which should be in my former PR. If you show me how to start on the documentation part, I can contribute.

**Comment by doganmeh** [comment]
Here is what the documentation I linked above says:

```
        """
        Builds a list of values provided by :py:attr:`.sources` looked up on the target ``obj``.
        Each source may provide a value as a 2-tuple of ``(default_value, rich_value)``, where
        ``default_value`` is the sortable raw value, and ``rich_value`` is possibly something else
        that can be coerced to a string for display purposes. The ``rich_value`` could also be a
        string with HTML in it.

        If no 2-tuple is given, then ``default_value`` and ``rich_value`` are taken to be the same.

        Columns with multiple :py:attr:`.sources` will have their ``rich_value`` coerced to a string
        and joined with :py:attr:`.separator`, and this new concatenated string becomes the final
        ``rich_value`` for the whole column.

        If all :py:attr:`.sources` are ``None``, :py:attr:`.empty_value` will be used as the
        ``rich_value``.
        """
```

I think a more common use case would be using rich value for coercing the values of the ManyToMany fields or the related objects via the use of the `.separator`. That would eliminate the need to create a custom processor for each and every MM field. Thoughts??

**Comment by tiliv** [comment]
> I think a more common use case would be using rich value for coercing the values of the ManyToMany fields or the related objects via the use of the .separator. That would eliminate the need to create a custom processor for each and every MM field. Thoughts??

The default behavior does attempt to join ManyToMany values with a space, but I never made it configurable in the quest to focus on doing single values very well—eventually, it seemed like offering a configuration path was pretty much just the same as providing a processor.

I'll close this, but the PR request I assume is still active, so I'll get to looking at it.
