### ISSUE TITLE
Live Demos for the Latest Version (0.9)

### ISSUE THREAD

**Issue by colindjk** [pivotal-energy-solutions/django-datatable-view#189]
Currently the link given in the readme (http://fixme) needs to be updated for 0.9, I understand that's why it's called "fixme". 

Does anyone have a link to a working version of django-datatables-view==0.9 with an outline similar to the one given on appspot that they could use for this link?

**Comment by tiliv** [comment]
We're trying to get it hosted somewhere (since faking the live demos kind of defeats the purpose of a mostly server-side code project), but you can clone the repository and run the demo site locally via the instructions in the README file just below that link.

Sorry of that inconvenience.  The live demo project uses an sqlite3 database so getting it to run should be fairly painless.
