### ISSUE TITLE
Is there any way to introduce html to the cells?

### ISSUE THREAD

**Issue by mezitax** [pivotal-energy-solutions/django-datatable-view#217]
Is there any way to introduce html to the cells?
i need some buttons but there is not something like a LinkColumn

**Comment by tiliv** [comment]
There's no dedicated column for that, but you can easily use the TextColumn and simply return html!  You do not need to use the Django ``mark_safe`` utility to make it render properly, either, since this is returned over an ajax call and the datatables.js library is responsible for rendering it.

**Comment by tiliv** [comment]
I should clarify, since I skipped over something about the setup—

Having the right column type on the field is what enables filter/sort features for ORM fields.  Whether you are shadowing a real field or declaring a custom one, you can specify the ``processor`` callback on the Datatable to be responsible for determining the value returned.  This allows you to intercept any model value and transform it if you want, or simply make up a custom column from scratch.

A common pattern for a simple anchor tag is this:

```python
from datatableview import helpers

class MyDatatable(Datatable):
    fkfield = columns.TextField(source='fkfield.name', processor=helpers.link_to_model)

    # Equivalent:
    fkfield = columns.TextField(source='fkfield.name', processor='get_fkfield_link')
    def get_fkfield_link(self, instance, *args, **kwargs):
        return helpers.link_to_model(instance)  # Uses the str() of instance by default
```
