### ISSUE TITLE
Support latest stable Datatable 1.10.X js

### ISSUE THREAD

**Issue by Rustem** [pivotal-energy-solutions/django-datatable-view#92]

**Comment by tiliv** [comment]
I will have this updated for the 1.0 release.  The 0.9 release will also include the fix, but I will use the dataTables.js legacy mode on by default for options so that we don't confuse people that aren't aware of how the DataTable js object has changed.

**Comment by 7wonders** [comment]
Any news on latest version. Looking forward to hacking on the buttons https://www.datatables.net/extensions/buttons/

**Comment by tiliv** [comment]
I will actually be pushing a bunch of changes during this upcoming week!  I'm excited about the new-style ``DataTable()`` configuration style and the way their api is cleaning  up.

**Comment by jangeador** [comment]
@7wonders have you done anything with buttons yet?

**Comment by 7wonders** [comment]
Not supported yet. Waiting on @tiliv :)

**Comment by tiliv** [comment]
0.9 Beta 2 is available in the github repository, which packages datatables.js version 1.10.9.  The initialization api is still the older style, but you can fetch the new api object from it.  It would actually be great if you could try it out and see if you are able to accomplish what you want with it.

For the 1.0 release (which is essentially the same as 0.9 just without the old config style and old datatables.js) I will swap it around to initialize the datatable with the new api too.

0.9 changes just about everything for declaring a datatable, even though the core concepts haven't changed.  You'll want to use the example project included in the code to do a local ``syncdb``, ``loaddata``, and then ``runserver``, so that you can see the new examples.  There's no independent demo site yet, so your the example project is your only access to the updated documentation for a little bit longer.
