### ISSUE TITLE
Issues with ColReorder

### ISSUE THREAD

**Issue by dotpmrcunha** [pivotal-energy-solutions/django-datatable-view#94]
Hi,
I am having issues using ColReorder from datatables. When I drag a column to another place and then I sort it, the server will sort using the initial column that was there. Is there anything that I need to do in order to make it work?

Thank you.

**Comment by tiliv** [comment]
I'm not certain I know what to do to fix this yet.  Essentially, the server side is assuming it knows the base configuration that the client is using.

I'd like to avoid allowing the client to push its own options to the server during ajax requests, but perhaps I can allow this for specifically the column order declaration.

I'll look for a fix for this in 1.0 (to be released within the month).  1.0 uses a superior column declaration syntax that will give internal names to all columns instead of this mangled verbosename stuff we use in 0.8 and earlier.  The mangled names would make the process of the js naming columns to the server for reorder a really lame process that I don't want to get into.

**Comment by tiliv** [comment]
I'm actually having trouble reproducing a sort issue in my 1.0 branch.  The ColReorder plugin all client-side manipulation of the DOM, and it actually seems to request sorting using the indexes that were used when the table was initialized.  There's actually nothing for me to do on the server-side to facilitate what it does.
